services:
  db:
    image: mysql:8.0
    container_name: stock_project-db
    restart: always
    environment:
      MYSQL_DATABASE: stockapp_db
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: stock_project-web
    command: >
      sh -c " /wait-for-mysql.sh python manage.py migrate && python manage.py runserver 0.0.0.0:8000 "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: stockapp_db
      DB_USER: root
      DB_PASSWORD: 1234

volumes:
  mysql_data:
